import { useEffect, useRef, useState } from 'react';
import { Wind, Upload, Box, SlidersHorizontal, Layers3, Play, ChartNoAxesCombined, Download, CircleCheck, CircleAlert, RotateCcw, Plus, ChevronRight } from 'lucide-react';
import Viewer from './Viewer';
import { api, post } from './api';
import { GeometryTools, PhysicsPanel, MeshPanel, RunPanel, ResultsPanel, ExportPanel } from './Panels';
import RunDetails, { TraceChart } from './RunDetails';

const steps = [['Geometry',Box],['Physics',SlidersHorizontal],['Mesh',Layers3],['Run',Play],['Results',ChartNoAxesCombined],['Export',Download]] as const;
export default function App(){
  const [step,setStep]=useState(0), [geometries,setGeometries]=useState<any[]>([]), [geometry,setGeometry]=useState<any>(),[spec,setSpec]=useState<any>(),[health,setHealth]=useState<any>();
  const [error,setError]=useState(''),[busy,setBusy]=useState(''),[units,setUnits]=useState('mm'),[reset,setReset]=useState(0),[wireframe,setWireframe]=useState(false),[selected,setSelected]=useState<string[]>([]);
  const [runs,setRuns]=useState<any[]>([]),[run,setRun]=useState<any>(),[logs,setLogs]=useState<string[]>([]),[report,setReport]=useState<any>(),[candidate,setCandidate]=useState<any>(),[field,setField]=useState('pressure_pa'),[colorRange,setColorRange]=useState<[number,number]>(),[viewPath,setViewPath]=useState<string>(),[comparison,setComparison]=useState('');
  const [samples,setSamples]=useState<any>();
  const runRef=useRef(run);runRef.current=run;
  async function refresh(){try{setGeometries(await api('/geometry'));setHealth(await api('/health'));}catch(e){setError(String(e));}}
  useEffect(()=>{refresh();const interval=setInterval(()=>{api('/health').then(setHealth).catch(()=>{});api<any[]>('/runs').then(list=>{setRuns(list);const r=runRef.current;const latest=r&&list.find(x=>x.id===r.id);if(latest&&latest.updated!==r.updated)api(`/runs/${r.id}`).then(detail=>setRun((current:any)=>current?.id===detail.id?detail:current)).catch(()=>{});}).catch(()=>{});},3000);return()=>clearInterval(interval);},[]);
  useEffect(()=>{setReport(undefined);},[spec]);
  useEffect(()=>{setLogs([]);setViewPath(undefined);setSamples(undefined);if(!run)return;const events=new EventSource(`/api/runs/${run.id}/events`);events.onmessage=e=>{const event=JSON.parse(e.data);if(event.message)setLogs(v=>[...v,event.message].slice(-250));};events.addEventListener('done',()=>{events.close();api(`/runs/${run.id}`).then(detail=>setRun((current:any)=>current?.id===detail.id?detail:current)).catch(()=>{});});return()=>events.close();},[run?.id]);
  async function choose(g:any){setGeometry(g);setSelected([]);setSpec(await api(`/geometry/${g.id}/defaults`));}
  function applySpec(s:any){setSpec(s);if(s.geometry_id!==geometry?.id)api(`/geometry/${s.geometry_id}`).then(g=>{setGeometry(g);setSelected([]);}).catch(e=>setError(String(e)));}
  async function act(label:string,action:()=>Promise<void>){setBusy(label);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('');}}
  async function upload(file:File){await act('Importing geometry',async()=>{const form=new FormData();form.append('file',file);form.append('units',units);const g=await api('/geometry/import',{method:'POST',body:form});await choose(g);await refresh();});}
  async function validate(){await act('Checking setup',async()=>setReport(await post('/validate',spec)));}
  async function launch(kind:string){await act(kind==='case'?'Generating case':'Queuing simulation',async()=>{const check=await post('/validate',spec);setReport(check);if(!check.valid)throw new Error(check.errors.join('; '));const source=kind==='solve'&&run?.kind==='mesh'&&run?.status==='completed'?`&mesh_run_id=${run.id}`:'';const r=await post(`/runs?kind=${kind}${source}`,spec);setRun(r);setRuns(await api('/runs'));if(kind!=='case')setStep(3);});}
  async function view(request:any,savedId?:string){setField(request.field);setSamples(undefined);async function show(id:string){if(runRef.current?.id!==run.id)return;setViewPath(`/api/runs/${run.id}/files/views/${id}/surface.vtp`);if(['line','probe'].includes(request.kind))setSamples({...await api(`/runs/${run.id}/views/${id}/samples`),kind:request.kind,id,run_id:run.id});}if(savedId){const path=`/api/runs/${run.id}/files/views/${savedId}/surface.vtp`;const r=await fetch(path,{method:'HEAD'});if(!r.ok)throw new Error('This saved extraction is still pending or failed; inspect run history');await show(savedId);return;}const saved=await post(`/runs/${run.id}/views`,request);const events=new EventSource(`/api/runs/${saved.job.id}/events`);events.addEventListener('done',async()=>{events.close();try{const job=await api(`/runs/${saved.job.id}`);if(job.status==='completed')await show(saved.id);else setError(job.error||'Extraction failed');}catch(e){setError(String(e));}});}
  const props={geometry,spec,setSpec:applySpec,act,selected,choose,refresh,busy};
  const resultUrl=step>=4&&run?.result.fields_available?(viewPath||`/api/runs/${run.id}/files/results/surface.vtp`):step===2&&run?.result.mesh_available?`/api/runs/${run.id}/files/mesh-preview.vtp`:undefined;
  useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools=[{name:'read_gustsim_workspace',title:'Read CFD workspace',description:'Read the current model, typed setup and run status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({geometry:geometry?.id,spec,run:run?{id:run.id,status:run.status}:null})},{name:'validate_gustsim_setup',title:'Validate simulation setup',description:'Run preflight validation on the current setup without launching CFD.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{if(!spec)throw new Error('Select geometry first');const r=await post('/validate',spec);setReport(r);return r;}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();},[geometry?.id,spec,run?.id,run?.status]);
  return <div className="app-shell">
    <header className="app-header"><a className="brand" href="/"><Wind size={27}/><span>gust<span>sim</span></span></a><span className="header-divider"/><span className="workspace-title">Engineering workspace</span><div className="header-right"><span className="local-badge"><i/> LOCAL WORKSPACE</span><span className="version">v0.1</span></div></header>
    <div className="workbench"><nav className="rail" aria-label="Workflow">{steps.map(([name,Icon],i)=><button key={name} className={step===i?'rail-item active':'rail-item'} onClick={()=>setStep(i)}><Icon size={22}/><span>{name}</span><small>{String(i+1).padStart(2,'0')}</small></button>)}<div className="rail-bottom">AIR<br/>WATER<br/><Wind size={20}/></div></nav>
    <aside className="setup-panel"><div className="panel-heading"><span className="eyebrow">SETUP / {String(step+1).padStart(2,'0')}</span><h1>{steps[step][0]}</h1><p>{step===0?'Prepare the model and identify its surfaces.':'Configure and inspect your simulation.'}</p></div>
      {error&&<div className="notice error" role="alert"><CircleAlert size={17}/><span>{error}</span></div>}{busy&&<div className="notice" role="status">{busy}…</div>}
      {step===0?<><section><h3>Import a model</h3><label className="dropzone"><Upload size={25}/><strong>Choose CAD geometry</strong><span>STEP or STL · up to 100 MB</span><input type="file" accept=".stl,.step,.stp" disabled={!!busy} onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value='';}}/></label><label className="field">STL source units<select value={units} onChange={e=>setUnits(e.target.value)}><option value="mm">Millimetres</option><option value="m">Metres</option><option value="cm">Centimetres</option><option value="in">Inches</option></select></label><p className="hint">STEP uses embedded units. Every revision is stored in metres.</p></section>
      <section><div className="section-title"><h3>Geometry library</h3><span>{geometries.length}</span></div>{geometries.length?geometries.map(g=><button className={`geometry-item ${geometry?.id===g.id?'selected':''}`} key={g.id} onClick={()=>act('Loading model',()=>choose(g))}><Box size={18}/><span><strong>{g.filename}</strong><small>{g.triangles.toLocaleString()} triangles · {g.patches.length} surfaces</small></span><ChevronRight size={16}/></button>):<p className="hint">Imported models and prepared revisions appear here.</p>}
      </section>
      {geometry&&<section><h3>Surface selection</h3><p className="hint">Click a surface in the viewport or select it below.</p><div className="patch-list">{geometry.patches.map((p:any)=><label key={p.name}><input type="checkbox" checked={selected.includes(p.name)} onChange={()=>setSelected(v=>v.includes(p.name)?v.filter(x=>x!==p.name):[...v,p.name])}/><span>{p.name}</span><small>{p.triangles}</small></label>)}</div></section>}<GeometryTools {...props} onCandidate={setCandidate}/></>:spec?<>
      {step===1&&<PhysicsPanel {...props}/>}{step===2&&<><MeshPanel {...props}/><section><button className="primary full" disabled={!health?.worker?.online||!!busy} onClick={()=>launch('mesh')}>Generate & check mesh</button></section></>}
      {step===3&&<RunPanel {...props} runs={runs} run={run} setRun={setRun} health={health} validation={report} onValidate={validate} onLaunch={launch}/>}
      {step===4&&<ResultsPanel run={run} act={act} onView={view} field={field} setField={setField} colorRange={colorRange} setColorRange={setColorRange}/>}
      {step===5&&<ExportPanel run={run} act={act} onLaunch={launch} busy={busy}/>}
      </>:<div className="section-placeholder"><SlidersHorizontal size={28}/><p>Import or create geometry to configure a simulation.</p></div>}
      <div className="panel-footer"><button className="primary full" disabled={!geometry} onClick={()=>setStep(Math.min(step+1,5))}>Continue to {steps[Math.min(step+1,5)][0].toLowerCase()}<ChevronRight size={17}/></button></div>
    </aside>
    <main className="main-surface"><div className="viewport-toolbar"><div><span className="eyebrow">MODEL VIEW</span><strong>{geometry?.filename||'No geometry selected'}</strong></div><div className="toolbar-actions"><button className={wireframe?'active':''} onClick={()=>setWireframe(v=>!v)} title="Toggle mesh edges"><Layers3 size={17}/> Edges</button><button onClick={()=>setReset(v=>v+1)} title="Reset camera"><RotateCcw size={17}/></button></div></div>
      {candidate&&<div className="candidate-banner"><span>Prepared revision · {candidate.triangles.toLocaleString()} triangles · {candidate.diagnostics.open_edges} open edges</span><button onClick={()=>act('Using prepared revision',async()=>{await choose(candidate);setCandidate(undefined);})}>Use revision</button><button onClick={()=>setCandidate(undefined)}>Return to original</button></div>}
      {step>=4&&<div className="comparison-toolbar"><label>Compare with <select value={comparison} onChange={e=>setComparison(e.target.value)}><option value="">Single view</option>{runs.filter(r=>r.result.fields_available&&r.id!==run?.id).map(r=><option key={r.id} value={r.id}>{r.spec.name}</option>)}</select></label><span>Field: {field} · {colorRange?'shared fixed range':'automatic ranges'}</span></div>}
      <div className={`viewer-row ${comparison&&step>=4?'comparison':''}`}><Viewer geometryId={candidate?.id||geometry?.id} resultUrl={resultUrl} field={field} colorRange={colorRange} wireframe={wireframe} reset={reset} onPick={id=>{const p=geometry?.patches.find((p:any)=>p.group===id);if(p)setSelected(v=>v.includes(p.name)?v.filter(x=>x!==p.name):[...v,p.name]);}}/>{comparison&&step>=4&&<Viewer resultUrl={`/api/runs/${comparison}/files/results/surface.vtp`} field={field} colorRange={colorRange} wireframe={wireframe}/>}</div>
      <div className="model-summary"><div><span>MODEL SIZE</span><strong>{geometry?geometry.dimensions.map((v:number)=>v.toPrecision(3)).join(' × ')+' m':'—'}</strong></div><div><span>SURFACE MESH</span><strong>{geometry?geometry.triangles.toLocaleString()+' triangles':'—'}</strong></div><div><span>GEOMETRY CHECK</span><strong className={geometry?.diagnostics.watertight?'good':''}>{geometry?(geometry.diagnostics.watertight?<><CircleCheck size={15}/> Closed surface</>:<><CircleAlert size={15}/> Open surface</>):'Awaiting import'}</strong></div></div>
      <div className="run-strip"><div><span className={`status-dot ${health?.worker?.online?'online':''}`}/><strong>{health?.worker?.online?'Compute worker ready':'Compute worker offline'}</strong><span>OpenFOAM {health?.openfoam_version||'2606'} · steady incompressible</span></div><small>{spec?'Configuration editable':'Geometry preparation available'}</small></div>
      {step===4&&samples&&<div className="run-details"><h3>{samples.kind==='line'?'Line sample':'Point probe'} · {field}</h3>{samples.kind==='line'?<TraceChart xLabel="Arc length · m" label={`Sampled ${field} versus arc length in metres`} series={[{name:field,color:'#71e1c3',values:samples.rows.filter((r:any)=>r.vtkValidPointMask!==0).map((r:any)=>[r.arc_length,field==='U'?Math.hypot(r['U:0'],r['U:1'],r['U:2']):r[field]])}]}/>:<div className="table-scroll"><table><tbody>{samples.columns.map((c:string)=><tr key={c}><th>{c}</th><td>{String(samples.rows[0]?.[c]??'Unavailable')}</td></tr>)}</tbody></table></div>}<a className="secondary spaced" href={`/api/runs/${samples.run_id}/files/views/${samples.id}/samples.csv`} download>Download samples · CSV</a></div>}
      {step>=3&&<RunDetails run={run} logs={logs}/>}
    </main></div><footer className="app-footer"><span>Single-phase air & water</span><span>Geometry → Setup → Mesh → Solve → Inspect</span><span>Numerical quality is evaluated per run</span></footer>
  </div>;
}
