import {useEffect, useState} from 'react';
import {api, post} from './api';
import {NumberField as N, VectorField as V, SelectField as S, Section} from './Controls';

export function ComponentTree({geometry,selected,setSelected,hidden,setHidden}:any){
  const [query,setQuery]=useState(''),[limit,setLimit]=useState(200);
  const parts=geometry.parts?.length?geometry.parts:geometry.patches.map((p:any)=>({id:p.name,name:p.name,patches:[p.name]}));
  return <Section title="Components"><label className="field">Find component<input value={query} onChange={e=>setQuery(e.target.value)}/></label><p className="hint">Select a component to select all its surfaces. The rotor belongs in the same assembly STEP.</p>
    <button className="secondary full" onClick={()=>setHidden([])}>Show all components</button>
    {parts.filter((p:any)=>p.name.toLowerCase().includes(query.toLowerCase())).slice(0,limit).map((p:any)=>{let depth=0,parent=p.parent_id;while(parent&&depth<64){depth++;parent=parts.find((q:any)=>q.id===parent)?.parent_id;}const checked=p.patches.length>0&&p.patches.every((n:string)=>selected.includes(n));return <div className="component-row" key={p.id||p.name} style={{paddingLeft:depth*12}}><label><input type="checkbox" checked={checked} onChange={()=>setSelected(checked?selected.filter((n:string)=>!p.patches.includes(n)):[...new Set([...selected,...p.patches])])}/><span title={p.id}>{p.name}</span></label><div><button onClick={()=>setHidden(p.patches.every((n:string)=>hidden.includes(n))?hidden.filter((n:string)=>!p.patches.includes(n)):[...new Set([...hidden,...p.patches])])}>{p.patches.every((n:string)=>hidden.includes(n))?'Show':'Hide'}</button><button onClick={()=>setHidden(geometry.patches.map((q:any)=>q.name).filter((n:string)=>!p.patches.includes(n)))}>Isolate</button></div></div>;})}
    {parts.filter((p:any)=>p.name.toLowerCase().includes(query.toLowerCase())).length>limit&&<button className="secondary full" onClick={()=>setLimit(v=>v+200)}>Show more components</button>}
  </Section>;
}

export function GuidedSetup({geometry,spec,setSpec,selected,act}:any){
  const [kind,setKind]=useState('aerodynamics'),[fluid,setFluid]=useState('air'),[speed,setSpeed]=useState(10),[direction,setDirection]=useState([1,0,0]),[lift,setLift]=useState([0,0,1]);
  const [inlet,setInlet]=useState(''),[outlet,setOutlet]=useState(''),[driving,setDriving]=useState('flow'),[flow,setFlow]=useState(.01),[pin,setPin]=useState(100),[pout,setPout]=useState(0),[turbulence,setTurbulence]=useState('kOmegaSST');
  const [origin,setOrigin]=useState([0,0,0]),[axis,setAxis]=useState([1,0,0]),[rpm,setRpm]=useState(2000),[preview,setPreview]=useState<any>(),[confirmed,setConfirmed]=useState(false),[refs,setRefs]=useState(false);
  const request={geometry_id:geometry.id,kind,fluid,turbulence,speed,direction,lift_axis:lift,inlet,outlet,driving,flow_rate:flow,inlet_pressure_pa:pin,outlet_pressure_pa:pout,patches:selected,origin,axis,rpm};
  const requestKey=JSON.stringify(request);
  useEffect(()=>{setPreview(undefined);setConfirmed(false);},[requestKey]);
  return <Section title="Guided setup"><p className="hint">Current setup: {spec.use_case?.kind||'Custom'}. Preview a common-use setup before replacing the current settings.</p>
    <S label="Common use" value={kind} onChange={v=>{setKind(v);setSpeed(v==='propeller'?0:10);if(v==='aerodynamics')setFluid('air');}} options={[["pipe","Basic pipe flow"],["aerodynamics","Object moving through air"],["propeller","Stationary assembly with rotor"]]}/>
    {kind!=='aerodynamics'&&<S label="Fluid at 20 °C" value={fluid} onChange={setFluid} options={['air','water']}/>}
    <S label="Turbulence" value={turbulence} onChange={setTurbulence} options={[["kOmegaSST","Fully turbulent k–ω SST"],["laminar","Laminar"]]}/>
    {kind==='pipe'?<><p className="hint">First isolate the inner walls and cap planar openings in Geometry. Select one cap for each end.</p><S label="Inlet surface" value={inlet} onChange={setInlet} options={[["","Choose inlet"],...geometry.patches.map((p:any)=>[p.name,p.name])]}/><S label="Outlet surface" value={outlet} onChange={setOutlet} options={[["","Choose outlet"],...geometry.patches.map((p:any)=>[p.name,p.name])]}/><S label="Driving condition" value={driving} onChange={setDriving} options={[["flow","Known volume flow"],["speed","Known mean inlet speed"],["pressure","Known pressures → predict flow"]]}/>{driving==='flow'?<N label="Volume flow · m³/s" value={flow} onChange={setFlow}/>:<N label={driving==='pressure'?'Turbulence reference speed estimate · m/s':'Mean inlet speed · m/s'} value={speed} onChange={setSpeed}/>}{driving==='pressure'&&<><N label="Inlet total pressure · Pa gauge" value={pin} onChange={setPin}/><p className="hint">The reference speed initializes turbulence; it does not prescribe the resulting flow.</p></>}<N label="Outlet static pressure · Pa gauge" value={pout} onChange={setPout}/></>:<><N label={kind==='propeller'?'Axial inflow · m/s (0 = still fluid)':'Travel speed · m/s'} value={speed} onChange={setSpeed}/>{kind==='aerodynamics'?<><V label="Object travel direction" value={direction} onChange={setDirection}/><V label="Positive lift direction" value={lift} onChange={setLift}/><p className="hint">Air flows opposite the travel direction. {selected.length} surfaces selected for force measurement.</p></>:<><V label="Rotor origin · m" value={origin} onChange={setOrigin}/><V label="Positive rotation axis" value={axis} onChange={setAxis}/><N label="Signed RPM · right-hand rule" value={rpm} onChange={setRpm}/><p className="hint">{selected.length} rotor surfaces selected. Confirm axis and origin here; the preview fits the region around these surfaces.</p></>}</>}
    <button className="secondary full spaced" onClick={()=>act('Generating setup preview',async()=>setPreview(await post('/presets/preview',request)))}>Preview suggested setup</button>
    {preview&&<div className="preset-preview"><h3>Review suggested settings</h3><p className="hint">Model dimensions: {geometry.dimensions.map((n:number)=>n.toPrecision(4)).join(' × ')} m</p><V label="Point inside intended fluid · m" value={preview.spec.domain.fluid_point} onChange={v=>{setConfirmed(false);setPreview({...preview,spec:{...preview.spec,domain:{...preview.spec.domain,fluid_point:v}}});}}/><details><summary>Domain, boundaries, mesh and reference directions</summary><pre className="log-output">{JSON.stringify(preview.spec,null,2)}</pre></details><label className="check-field"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I checked dimensions, fluid point, directions and selected surfaces</label><label className="check-field"><input type="checkbox" checked={refs} onChange={e=>setRefs(e.target.checked)}/> Reference area and length are suitable for coefficients</label><button className="primary full" disabled={!confirmed} onClick={()=>act('Applying guided setup',async()=>{const s={...preview.spec,use_case:{...preview.spec.use_case,confirmed:true,references_confirmed:refs}};setSpec(s);setPreview(undefined);})}>Apply reviewed setup</button><p className="hint">Standard mesh and SST settings are starting points. Experimental validation remains pending.</p></div>}
  </Section>;
}

export function AutomaticViews({run,onView,act}:any){
  const [views,setViews]=useState<any[]>([]);
  useEffect(()=>{setViews([]);if(!run?.result.fields_available)return;let alive=true;const refresh=()=>api<any[]>(`/runs/${run.id}/views`).then(v=>{if(alive)setViews(v.filter(item=>item.automatic));}).catch(()=>{});refresh();const timer=setInterval(refresh,3000);return()=>{alive=false;clearInterval(timer);};},[run?.id,run?.result.fields_available]);
  if(!run?.spec.use_case)return null;
  return <Section title="Suggested result views">{views.length?views.map(v=><button className="secondary full" key={v.id} disabled={v.status!=='completed'} onClick={()=>act('Opening saved view',()=>onView(v.spec,v.id))}>{v.spec.kind==='surface'?'Surface pressure':'Longitudinal velocity'} · {v.status||'queued'}{v.error&&<small>{v.error}</small>}</button>):<p className="hint">Views are queued automatically after solved fields are available.</p>}</Section>;
}
