import { useEffect, useState } from 'react';
import { Check, Download, Layers3, Play, Plus, Save, Square, RefreshCw } from 'lucide-react';
import { api, post } from './api';
import { NumberField as N, VectorField as V, SelectField as S, Section, fmt } from './Controls';

type Props={geometry:any;spec:any;setSpec:(s:any)=>void;act:(label:string,action:()=>Promise<void>)=>Promise<void>;selected:string[];choose:(g:any)=>Promise<void>;refresh:()=>Promise<void>;busy:string};
export function GeometryTools({geometry,spec,setSpec,act,selected,choose,refresh,busy,onCandidate}:Props&{onCandidate:(g:any)=>void}){
  const [shape,setShape]=useState('box'),[role,setRole]=useState('solid'),[radius,setRadius]=useState(.5),[inner,setInner]=useState(.4),[length,setLength]=useState(1),[dimensions,setDimensions]=useState([1,1,1]),[center,setCenter]=useState([0,0,0]),[axis,setAxis]=useState([1,0,0]),[name,setName]=useState('object'),[append,setAppend]=useState(false),[scale,setScale]=useState(1),[rotation,setRotation]=useState([0,0,0]),[translation,setTranslation]=useState([0,0,0]),[angle,setAngle]=useState(35),[mergeName,setMergeName]=useState('selected');
  async function prepare(body:any){await act('Preparing revision',async()=>{onCandidate(await post(`/geometry/${geometry.id}/prepare`,body));await refresh();});}
  return <>
    <Section title="Add setup geometry"><S label="Shape" value={shape} onChange={setShape} options={['box','sphere','cylinder',['tube','Hollow cylinder']]}/><S label="Role" value={role} onChange={setRole} options={[["solid","Physical solid"],["enclosure","Fluid envelope"],["refinement","Refinement region"],["rotation","Rotating region"]]}/><label className="field">Name<input value={name} onChange={e=>setName(e.target.value)}/></label>
    {shape==='box'?<V label="Dimensions · m" value={dimensions} onChange={setDimensions}/>:<N label="Outer radius · m" value={radius} onChange={setRadius} min={.00001}/>} {shape==='tube'&&<N label="Inner radius · m" value={inner} onChange={setInner}/>}{['tube','cylinder'].includes(shape)&&<><N label="Length · m" value={length} onChange={setLength}/><V label="Axis" value={axis} onChange={setAxis}/></>}<V label="Center · m" value={center} onChange={setCenter}/>
    {geometry&&['solid','enclosure'].includes(role)&&<label className="check-field"><input type="checkbox" checked={append} onChange={e=>setAppend(e.target.checked)}/> Add to current geometry</label>}
    {shape==='tube'&&role==='enclosure'&&<p className="hint">Creates the inner fluid cylinder with end caps. Use physical solid to create the tube material.</p>}
    <button className="secondary full" disabled={!!busy} onClick={()=>act('Adding geometry',async()=>{const p={shape,role,name,center,dimensions,radius,inner_radius:inner,length,axis};if(role==='refinement'){if(!spec)throw new Error('Select a model first');setSpec({...spec,regions:[...spec.regions,p]});}else if(role==='rotation'){if(!spec)throw new Error('Select rotor geometry first');if(shape!=='cylinder')throw new Error('Use a cylinder for the rotating region');setSpec({...spec,rotation:{...spec.rotation,enabled:true,origin:center,axis,radius,length,blade_radius:radius*.8,patches:selected}});}else{const g=await post('/geometry/primitive'+(append&&geometry?`?parent_id=${geometry.id}`:''),p);await choose(g);await refresh();}})}><Plus size={16}/> Add {role==='rotation'||role==='refinement'?'region':'geometry'}</button></Section>
    {geometry&&<><Section title="Transform & repair"><N label="Scale multiplier" value={scale} onChange={setScale}/><V label="Rotation · degrees (XYZ)" value={rotation} onChange={setRotation}/><V label="Translation · m" value={translation} onChange={setTranslation}/><button className="secondary full" disabled={!!busy} onClick={()=>prepare({scale,rotation_deg:rotation,translation})}>Preview transform</button><button className="secondary full" disabled={!!busy} onClick={()=>prepare({repair:true})}>Auto prepare · preview safe repairs</button><p className="hint">Repair removes duplicate and degenerate triangles, welds coincident vertices, and fixes normals. It does not automatically fill openings.</p></Section>
    <Section title="Surface preparation"><label className="field">Merged surface name<input value={mergeName} onChange={e=>setMergeName(e.target.value)}/></label><button className="secondary full" disabled={!selected.length||!!busy} onClick={()=>prepare({merge_patches:selected,merged_name:mergeName})}>Merge {selected.length} selected surfaces</button><button className="secondary full" disabled={!selected.length||!!busy} onClick={()=>prepare({keep_patches:selected})}>Isolate selected inner walls</button><N label="Grouping angle · degrees" value={angle} onChange={setAngle}/><button className="secondary full" onClick={()=>act('Regrouping surfaces',async()=>onCandidate(await post(`/geometry/${geometry.id}/regroup?angle=${angle}`,{})))}>Regroup by angle</button></Section>
    <Section title="Geometry diagnostics"><dl className="diagnostic-list">{['open_edges','nonmanifold_edges','duplicate_faces','degenerate_faces','small_faces','components'].map(k=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{geometry.diagnostics[k]}</dd></div>)}</dl><p className="hint">Triangle self-intersections have not been certified.</p>{geometry.diagnostics.open_loops.map((loop:any)=><button key={loop.id} className="secondary full" disabled={!loop.planar||!!busy} onClick={()=>prepare({cap_loops:[loop.id]})}>Cap opening {loop.id+1} {loop.planar?'· planar':'· non-planar'}</button>)}</Section></>}
  </>;
}

export function PhysicsPanel({geometry,spec,setSpec,selected,act}:Props){
  const [boundaryPage,setBoundaryPage]=useState(0);
  const [boundarySearch,setBoundarySearch]=useState(''),[boundaryKind,setBoundaryKind]=useState('all'),[boundaryComponent,setBoundaryComponent]=useState('all');
  const [kind,setKind]=useState('wall'),[bcPressure,setBcPressure]=useState(0),[bcFlow,setBcFlow]=useState(.01),[bcVelocity,setBcVelocity]=useState([0,0,0]),[bcRpm,setBcRpm]=useState(1000),[raw,setRaw]=useState(''),[rawOpen,setRawOpen]=useState(false);
  const change=(group:string,key:string,value:any)=>setSpec({...spec,[group]:{...spec[group],[key]:value},...(group==='rotation'&&key==='patches'&&spec.use_case?.kind==='propeller'?{use_case:{...spec.use_case,force_patches:value}}:{})});
  useEffect(()=>setBoundaryPage(0),[boundarySearch,boundaryKind,boundaryComponent,geometry.id]);
  const matchedBoundaries=spec.boundaries.map((b:any,i:number)=>({b,i})).filter(({b}:any)=>b.patch.toLowerCase().includes(boundarySearch.toLowerCase())&&(boundaryKind==='all'||b.kind===boundaryKind)&&(boundaryComponent==='all'||geometry.parts?.find((p:any)=>(p.id||p.name)===boundaryComponent)?.patches.includes(b.patch)));
  const missingBoundaries=geometry.patches.filter((p:any)=>!spec.boundaries.some((b:any)=>b.patch===p.name));
  const visibleBoundaries=matchedBoundaries.slice(boundaryPage*100,(boundaryPage+1)*100);
  const boundaryOptions=[['velocity_inlet','Velocity inlet'],['flow_inlet','Volume-flow inlet'],['pressure_inlet','Total-pressure inlet'],['pressure_outlet','Static-pressure outlet'],['wall','Stationary wall'],['moving_wall','Moving wall'],['rotating_wall','Rotating wall'],['symmetry','Symmetry'],['slip','Slip'],['freestream','Freestream']] as [string,string][];
  return <><Section title="Simulation template"><label className="field">Study name<input value={spec.name} onChange={e=>setSpec({...spec,name:e.target.value})}/></label><S label="Flow type" value={spec.mode} options={[["external","External flow"],["internal","Internal flow"],["rotor","Steady rotor · MRF"]]} onChange={v=>act('Changing flow template',async()=>{
    if(v==='internal')setSpec({...spec,use_case:null,mode:v,rotation:{...spec.rotation,enabled:false},boundaries:spec.boundaries.filter((b:any)=>geometry.patches.some((p:any)=>p.name===b.patch)),domain:{...spec.domain,fluid_point:geometry.bounds[0].map((x:number,i:number)=>(x+geometry.bounds[1][i])/2)}});
    else {const defaults=await api(`/geometry/${geometry.id}/defaults`);setSpec({...spec,use_case:null,mode:v,boundaries:[...defaults.boundaries.filter((b:any)=>!geometry.patches.some((p:any)=>p.name===b.patch)),...spec.boundaries.filter((b:any)=>geometry.patches.some((p:any)=>p.name===b.patch))],rotation:{...spec.rotation,enabled:v==='rotor'}});}
  })}/>{spec.mode==='internal'&&<p className="hint">Use a closed fluid envelope: isolate the inner walls, cap planar openings, then assign inlet and outlet conditions to the caps.</p>}</Section>
  <Section title="Fluid properties"><S label="Material at 20 °C" value={spec.fluid.name} onChange={v=>setSpec({...spec,fluid:{...spec.fluid,name:v,...(v==='air'?{density:1.204,dynamic_viscosity:1.825e-5,speed_of_sound:343}:{density:998.2,dynamic_viscosity:.001002,speed_of_sound:1482})}})} options={['air','water','custom']}/><div className="two-columns"><N label="Density · kg/m³" value={spec.fluid.density} onChange={v=>change('fluid','density',v)}/><N label="Viscosity · Pa·s" value={spec.fluid.dynamic_viscosity} onChange={v=>change('fluid','dynamic_viscosity',v)}/></div><N label="Absolute reference pressure · Pa" value={spec.fluid.reference_pressure_pa} onChange={v=>change('fluid','reference_pressure_pa',v)}/><p className="hint">Boundary pressures are gauge pressures. Density and viscosity are constant throughout this simulation.</p></Section>
  <Section title="Incident flow"><N label="Reference speed · m/s" value={spec.flow.speed} onChange={v=>change('flow','speed',v)}/><div className="two-columns"><N label="Angle of attack · °" value={spec.flow.alpha_deg} onChange={v=>change('flow','alpha_deg',v)}/><N label="Sideslip · °" value={spec.flow.beta_deg} onChange={v=>change('flow','beta_deg',v)}/></div><S label="Turbulence model" value={spec.flow.turbulence} onChange={v=>change('flow','turbulence',v)} options={[["kOmegaSST","k–ω SST · fully turbulent"],["laminar","Laminar"]]}/>{spec.flow.turbulence!=='laminar'&&<><N label="Turbulence intensity · fraction" value={spec.flow.intensity} onChange={v=>change('flow','intensity',v)}/><N label="Turbulence length scale · m" value={spec.flow.length_scale} onChange={v=>change('flow','length_scale',v)}/></>}</Section>
  <Section title="Domain & fluid region"><V label="Domain minimum · m" value={spec.domain.minimum} onChange={v=>change('domain','minimum',v)}/><V label="Domain maximum · m" value={spec.domain.maximum} onChange={v=>change('domain','maximum',v)}/><V label="Point inside the fluid · m" value={spec.domain.fluid_point} onChange={v=>change('domain','fluid_point',v)}/></Section>
  <Section title="Boundary conditions"><p className="hint">Assign each surface below, or apply a condition to the selected model surfaces.</p>{missingBoundaries.length>0&&<p className="finding fail">{missingBoundaries.length} surfaces need assignment after preparation. Select them in Components or the viewport, choose a condition, then Assign selected surfaces.</p>}<S label={`Condition for ${selected.length} selected surfaces`} value={kind} onChange={setKind} options={boundaryOptions}/>{['pressure_inlet','pressure_outlet'].includes(kind)&&<N label="Pressure · Pa gauge" value={bcPressure} onChange={setBcPressure}/>} {kind==='flow_inlet'&&<N label="Volume flow · m³/s" value={bcFlow} onChange={setBcFlow}/>} {['moving_wall','velocity_inlet'].includes(kind)&&<V label="Velocity · m/s" value={bcVelocity} onChange={setBcVelocity}/>} {kind==='rotating_wall'&&<N label="Wall rotation · RPM" value={bcRpm} onChange={setBcRpm}/>}<button className="secondary full" disabled={!selected.length} onClick={()=>setSpec({...spec,boundaries:[...spec.boundaries,...missingBoundaries.filter((p:any)=>selected.includes(p.name)).map((p:any)=>({patch:p.name}))].map((b:any)=>selected.includes(b.patch)?{...b,kind,pressure_pa:bcPressure,flow_rate:bcFlow,velocity:['moving_wall','velocity_inlet'].includes(kind)?bcVelocity:null,rpm:bcRpm,axis:spec.rotation.axis,origin:spec.rotation.origin}:b)})}>Assign selected surfaces</button>
  <label className="field">Find boundary<input value={boundarySearch} onChange={e=>setBoundarySearch(e.target.value)}/></label><S label="Filter by assignment" value={boundaryKind} onChange={setBoundaryKind} options={[["all","All assignments"],...boundaryOptions]}/><S label="Filter by component" value={boundaryComponent} onChange={setBoundaryComponent} options={[["all","All components"],...(geometry.parts||[]).map((p:any)=>[p.id||p.name,p.name])]}/><p className="hint">{matchedBoundaries.length} matching boundaries · page {boundaryPage+1} of {Math.max(1,Math.ceil(matchedBoundaries.length/100))}</p><div className="two-columns"><button className="secondary" disabled={boundaryPage===0} onClick={()=>setBoundaryPage(v=>v-1)}>Previous boundaries</button><button className="secondary" disabled={(boundaryPage+1)*100>=matchedBoundaries.length} onClick={()=>setBoundaryPage(v=>v+1)}>Next boundaries</button></div><div className="boundary-list">{visibleBoundaries.map(({b,i}:any)=><details key={b.patch}><summary><span>{b.patch}</span><small>{b.kind.replaceAll('_',' ')}</small></summary><S label="Boundary type" value={b.kind} options={boundaryOptions} onChange={v=>setSpec({...spec,boundaries:spec.boundaries.map((q:any,j:number)=>j===i?{...q,kind:v}:q)})}/>{['pressure_inlet','pressure_outlet'].includes(b.kind)&&<N label="Pressure · Pa gauge" value={b.pressure_pa} onChange={v=>setSpec({...spec,boundaries:spec.boundaries.map((q:any,j:number)=>j===i?{...q,pressure_pa:v}:q)})}/>} {b.kind==='flow_inlet'&&<N label="Flow rate · m³/s" value={b.flow_rate} onChange={v=>setSpec({...spec,boundaries:spec.boundaries.map((q:any,j:number)=>j===i?{...q,flow_rate:v}:q)})}/>} {['moving_wall','velocity_inlet'].includes(b.kind)&&<><label className="check-field"><input type="checkbox" checked={b.velocity===null} onChange={e=>setSpec({...spec,boundaries:spec.boundaries.map((q:any,j:number)=>j===i?{...q,velocity:e.target.checked?null:[0,0,0]}:q)})}/> Use incident velocity</label>{b.velocity&&<V label="Velocity · m/s" value={b.velocity} onChange={v=>setSpec({...spec,boundaries:spec.boundaries.map((q:any,j:number)=>j===i?{...q,velocity:v}:q)})}/>}</>}</details>)}</div></Section>
  <Section title="Rotating region"><p className="hint">One steady MRF region predicts mean loads with a fixed rotor position. It does not resolve blade-passing motion.</p><label className="check-field"><input type="checkbox" checked={spec.rotation.enabled} onChange={e=>change('rotation','enabled',e.target.checked)}/> Enable steady MRF</label>{spec.rotation.enabled&&<><V label="Rotation origin · m" value={spec.rotation.origin} onChange={v=>change('rotation','origin',v)}/><V label="Rotation axis" value={spec.rotation.axis} onChange={v=>change('rotation','axis',v)}/><N label="Signed RPM · right-hand rule" value={spec.rotation.rpm} onChange={v=>change('rotation','rpm',v)}/><N label="Blade radius · m" value={spec.rotation.blade_radius} onChange={v=>change('rotation','blade_radius',v)}/><N label="Region radius · m" value={spec.rotation.radius} onChange={v=>change('rotation','radius',v)}/><N label="Region length · m" value={spec.rotation.length} onChange={v=>change('rotation','length',v)}/><button className="secondary full" disabled={!selected.length} onClick={()=>change('rotation','patches',selected)}>Use {selected.length} selected rotor surfaces</button><button className="secondary full spaced" disabled={!selected.length} onClick={()=>act('Fitting rotating region',async()=>{const suggested=await post(`/geometry/${geometry.id}/rotor-suggestion`,{patches:selected,axis:spec.rotation.axis,origin:spec.rotation.origin});setSpec({...spec,rotation:{...spec.rotation,...suggested},...(spec.use_case?.kind==='propeller'?{use_case:{...spec.use_case,force_patches:selected}}:{})});})}>Confirm axis/origin and suggest cylinder</button><p className="hint">Rotor: {spec.rotation.patches.join(', ')||'No surfaces selected'}. Other surfaces remain stationary. At zero freestream speed, open ambient boundaries use total pressure and allow inflow/outflow. Blade-passing loads are not resolved.</p></>}</Section>
  <Section title="Reference quantities">{spec.use_case&&<><label className="check-field"><input type="checkbox" checked={spec.use_case.confirmed} onChange={e=>setSpec({...spec,use_case:{...spec.use_case,confirmed:e.target.checked}})}/> I checked dimensions, fluid point, directions and selected surfaces</label><label className="check-field"><input type="checkbox" checked={spec.use_case.references_confirmed} onChange={e=>setSpec({...spec,use_case:{...spec.use_case,references_confirmed:e.target.checked}})}/> Reference area and length confirmed for coefficients</label></>}<N label="Reference area · m²" value={spec.references.area} onChange={v=>change('references','area',v)}/><N label="Reference length · m" value={spec.references.length} onChange={v=>change('references','length',v)}/><V label="Moment origin · m" value={spec.references.origin} onChange={v=>change('references','origin',v)}/><V label="Drag axis" value={spec.references.drag_axis} onChange={v=>change('references','drag_axis',v)}/><V label="Lift axis" value={spec.references.lift_axis} onChange={v=>change('references','lift_axis',v)}/><V label="Positive thrust axis" value={spec.references.thrust_axis||[-1,0,0]} onChange={v=>change('references','thrust_axis',v)}/></Section>
  <Section title="Advanced configuration"><button className="secondary full" onClick={()=>{setRaw(JSON.stringify(spec,null,2));setRawOpen(v=>!v);}}>Edit typed configuration</button>{rawOpen&&<><label className="field">Simulation JSON<textarea rows={18} value={raw} onChange={e=>setRaw(e.target.value)}/></label><button className="secondary full" onClick={()=>act('Validating configuration',async()=>{const parsed=JSON.parse(raw);await post('/validate',parsed);setSpec(parsed);setRawOpen(false);})}>Apply configuration</button></>}</Section></>;
}

export function MeshPanel({spec,setSpec}:Props){const change=(key:string,v:any)=>setSpec({...spec,mesh:{...spec.mesh,[key]:v}});return <><Section title="Mesh resolution"><S label="Preset" value={spec.mesh.preset} options={['draft','standard','refined']} onChange={v=>{const p:any={draft:{base_cells:18,surface_level:1,feature_level:2,layers:0},standard:{base_cells:24,surface_level:2,feature_level:3,layers:3},refined:{base_cells:36,surface_level:3,feature_level:4,layers:5}};setSpec({...spec,mesh:{...spec.mesh,preset:v,...p[v]}});}}/><p className="hint">Resolution presets are not accuracy guarantees. Compare multiple mesh resolutions before relying on loads.</p><N label="Cells along longest domain axis" value={spec.mesh.base_cells} onChange={v=>change('base_cells',v)} step={1}/><N label="Surface refinement level" value={spec.mesh.surface_level} onChange={v=>change('surface_level',v)} step={1}/><N label="Feature refinement level" value={spec.mesh.feature_level} onChange={v=>change('feature_level',v)} step={1}/><N label="Local body refinement level" value={spec.mesh.body_level||0} onChange={v=>setSpec({...spec,mesh:{...spec.mesh,body_level:v}})}/><p className="hint">Higher levels resolve smaller details around the object. Each level halves the cell size. If a surface disappears, increase this level and regenerate.</p><N label="Maximum cells" value={spec.mesh.max_cells} onChange={v=>change('max_cells',v)} step={10000}/></Section>
  <Section title="Boundary layers"><S label="Wall treatment" value={spec.mesh.wall_treatment} options={[["wall_function","Wall functions"],["resolved","Wall resolved"]]} onChange={v=>change('wall_treatment',v)}/><N label="Prism layers" value={spec.mesh.layers} onChange={v=>change('layers',v)} step={1}/><N label="First layer thickness · m" value={spec.mesh.first_layer_m} onChange={v=>change('first_layer_m',v)}/><N label="Layer expansion ratio" value={spec.mesh.expansion_ratio} onChange={v=>change('expansion_ratio',v)}/><p className="hint">Inspect achieved layer coverage and y+ after meshing and solving. Requested layers are not guaranteed everywhere.</p></Section>
  <Section title="Refinement regions"><p className="hint">A wake region is generated along the incident flow. Additional regions can be added under Geometry.</p>{spec.regions.map((r:any,i:number)=><div className="region-item" key={i}><span>{r.name} · {r.shape}</span><button onClick={()=>setSpec({...spec,regions:spec.regions.filter((_:any,j:number)=>i!==j)})}>Remove</button></div>)}</Section></>;}

export function RunPanel({spec,setSpec,act,runs,run,setRun,health,validation,onValidate,onLaunch,busy,solveReady,setupReady}:any){const [parameter,setParameter]=useState('speed'),[values,setValues]=useState('10, 20, 30'),[setups,setSetups]=useState<any[]>([]);return <><Section title="Solver controls"><N label="Parallel processes" value={spec.solver.processes} onChange={v=>setSpec({...spec,solver:{...spec.solver,processes:v}})} step={1}/><N label="Maximum SIMPLE iterations" value={spec.solver.iterations} onChange={v=>setSpec({...spec,solver:{...spec.solver,iterations:v}})} step={1}/><N label="Write interval · iterations" value={spec.solver.write_interval} onChange={v=>setSpec({...spec,solver:{...spec.solver,write_interval:v}})} step={1}/><N label="Residual target" value={spec.solver.residual_target} onChange={v=>setSpec({...spec,solver:{...spec.solver,residual_target:v}})}/><N label="Stage time limit · minutes" value={spec.solver.timeout_minutes} onChange={v=>setSpec({...spec,solver:{...spec.solver,timeout_minutes:v}})} step={1}/></Section>
  <Section title="Preflight"><button className="secondary full" disabled={!!busy} onClick={onValidate}><Check size={16}/> Check setup</button>{validation&&<><div className={`validation-status ${validation.valid?'good':'bad'}`}>{validation.valid?'Setup checks passed':'Setup needs attention'}</div><p className="hint">Re {fmt(validation.reynolds)} · estimated Mach {fmt(validation.estimated_mach,3)}</p>{validation.errors.map((s:string)=><p className="finding fail" key={s}>{s}</p>)}{validation.warnings.map((s:string)=><p className="finding warning" key={s}>{s}</p>)}</>}</Section>
  <Section title="Compute">{!solveReady&&<p className="hint">Complete Setup, then generate and review a compatible mesh before running.</p>}<p className="hint">{health?.worker?.online?'One job at a time. Closing this page will not stop a run.':'Start the Linux worker to mesh and solve. Case export is available without it.'}</p><button className="secondary full" disabled={!!busy||!health?.worker?.online||!setupReady} onClick={()=>onLaunch('mesh')}><Layers3 size={16}/> Generate & check mesh</button><button className="primary full spaced" disabled={!!busy||!health?.worker?.online||!solveReady} onClick={()=>onLaunch('solve')}><Play size={16}/> Run simulation</button>{run&&['queued','running'].includes(run.status)&&<button className="secondary full" onClick={()=>act('Cancelling',async()=>setRun(await post(`/runs/${run.id}/cancel`,{})))}><Square size={15}/> Cancel this attempt</button>}</Section>
  <Section title="Parameter study"><S label="Sweep parameter" value={parameter} onChange={setParameter} options={[["speed","Speed · m/s"],["alpha_deg","Angle of attack · °"],["rpm","Rotor RPM"],["surface_level","Mesh surface level"]]}/><label className="field">Comma-separated values<input value={values} onChange={e=>setValues(e.target.value)}/></label><button className="secondary full" disabled={!health?.worker?.online||!!busy} onClick={()=>act('Creating study',async()=>{const study=await post('/studies?guided=true',{spec,parameter,values:values.split(',').map(v=>Number(v.trim()))});setRun(study.runs[0]);})}>Queue mesh study</button><p className="hint">Each variant starts with a mesh attempt. Load its setup and review the mesh before solving.</p></Section>
  <Section title="Saved setup"><button className="secondary full" onClick={()=>act('Saving setup',async()=>{await post('/setups',spec);setSetups(await api('/setups'));})}><Save size={16}/> Save configuration</button><button className="secondary full" onClick={()=>act('Loading configurations',async()=>setSetups(await api('/setups')))}>Show saved configurations</button>{setups.map(s=><button className="geometry-item" key={s.id} onClick={()=>act('Loading configuration',async()=>setSpec(s.spec))}>{s.name}</button>)}</Section>
  <Section title="Run history">{run?.spec.geometry_id&&<button className="secondary full" onClick={()=>setSpec(run.spec)}>Load this attempt’s setup</button>}{runs.length?runs.map((r:any)=><button key={r.id} className={`geometry-item ${run?.id===r.id?'selected':''}`} onClick={()=>setRun(r)}><span><strong>{r.spec.name||'Result extraction'}</strong><small>{r.kind} · {r.status} · {r.id.slice(0,6)}</small></span></button>):<p className="hint">No runs yet.</p>}{run&&!['queued','running'].includes(run.status)&&<button className="secondary full" onClick={()=>act('Retrying run',async()=>setRun(await post(`/runs/${run.id}/retry?guided=true`,{})))}><RefreshCw size={15}/> {run.kind==='solve'?'Create mesh attempt to retry':'Retry as a new attempt'}</button>}</Section></>;}

export function ResultsPanel({run,act,onView,setField,field,colorRange,setColorRange}:any){const [kind,setKind]=useState('surface'),[origin,setOrigin]=useState([0,0,0]),[normal,setNormal]=useState([0,0,1]),[end,setEnd]=useState([1,0,0]),[radius,setRadius]=useState(.2),[saved,setSaved]=useState<any[]>([]);return <><Section title="Inspect fields"><S label="Field" value={field} onChange={setField} options={[["pressure_pa","Pressure · Pa gauge"],["U","Velocity · m/s"],["vorticity","Vorticity · 1/s"],["yPlus","Wall y+"]]}/><S label="View" value={kind} onChange={setKind} options={['surface','slice','clip','streamlines','glyphs','line','probe']}/>{kind!=='surface'&&<V label="Origin · m" value={origin} onChange={setOrigin}/>} {['slice','clip'].includes(kind)&&<V label="Normal" value={normal} onChange={setNormal}/>} {kind==='line'&&<V label="End point · m" value={end} onChange={setEnd}/>} {kind==='streamlines'&&<N label="Seed radius · m" value={radius} onChange={setRadius}/>}<label className="check-field"><input type="checkbox" checked={!!colorRange} onChange={e=>setColorRange(e.target.checked?[0,100]:undefined)}/> Fixed color range for comparisons</label>{colorRange&&<div className="two-columns"><N label="Minimum" value={colorRange[0]} onChange={v=>setColorRange([v,colorRange[1]])}/><N label="Maximum" value={colorRange[1]} onChange={v=>setColorRange([colorRange[0],v])}/></div>}<button className="secondary full" disabled={!run?.result.fields_available} onClick={()=>act('Extracting view',async()=>{if(colorRange&&colorRange[1]<=colorRange[0])throw new Error('Color maximum must exceed minimum');await onView({kind,field,origin,normal,end,seed_radius:radius,resolution:100,color_range:colorRange||null});})}>Extract & save view</button><p className="hint">Geometry coloring is not a simulation result. Fields appear only after a real solve and postprocessing.</p></Section>
  <Section title="Saved views"><button className="secondary full" disabled={!run} onClick={()=>act('Loading saved views',async()=>setSaved(await api(`/runs/${run.id}/views`)))}>Show saved views</button>{saved.map(v=><button key={v.id} className="geometry-item" onClick={()=>act('Loading saved view',()=>onView(v.spec,v.id))}>{v.spec.kind} · {v.spec.field}</button>)}</Section>
  <Section title="Numerical quality">{run?.result.findings?.length?run.result.findings.map((f:any)=><p key={f.code} className={`finding ${f.status}`}><strong>{f.code.replaceAll('_',' ')} · {f.status}</strong><br/>{f.detail}</p>):<p className="hint">Quality checks become available after solving.</p>}</Section></>;}

export function ExportPanel({run,act,onLaunch,busy}:any){return <><Section title="Reproducible case"><p className="hint">Export an editable OpenFOAM v2606 case with the exact geometry, settings, and provenance.</p><button className="secondary full" disabled={!!busy} onClick={()=>onLaunch('case')}>Generate case without solving</button></Section><Section title="Download data"><p className="hint">Unavailable exports are disabled until their required artifact exists.</p>{([['case','OpenFOAM case · ZIP'],['bundle','Complete results bundle · ZIP'],['csv','Force & moment history · CSV'],['vtk','Volume mesh & fields · VTU'],['hdf5','Python / MATLAB fields · HDF5'],['paraview','ParaView state · PVSM'],['png','Rendered view · PNG'],['report','Engineering report · HTML']] as const).map(([kind,label])=><button className="secondary full" key={kind} title={run?.result.export_available?.[kind]?label:"Required artifact unavailable"} disabled={!run?.result.export_available?.[kind]} onClick={()=>act('Preparing export',async()=>{const r=await fetch(`/api/runs/${run.id}/export/${kind}`);if(!r.ok){const e=await r.json();throw new Error(e.detail);}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=r.headers.get('content-disposition')?.match(/filename="?([^";]+)/)?.[1]||`gustsim-${kind}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}><Download size={16}/>{label}</button>)}</Section><Section title="Data conventions"><p className="hint">SI units. Pressure is exported in gauge pascals; raw OpenFOAM pressure is kinematic. HDF5 preserves cell and point associations, mesh topology, and configuration metadata. Iteration histories are not physical time.</p></Section></>;}
