import { fmt } from './Controls';
export function TraceChart({series,logarithmic=false,label,xLabel='SIMPLE iteration'}:{series:{name:string;color:string;values:[number,number][]}[];logarithmic?:boolean;label:string;xLabel?:string}){
  const all=series.flatMap(s=>s.values).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1])&&(!logarithmic||p[1]>0));
  if(!all.length)return <div className="chart-empty">{label} appears after a solve.</div>;
  const transform=(v:number)=>logarithmic?Math.log10(Math.max(v,1e-16)):v;
  const minX=Math.min(...all.map(p=>p[0])),maxX=Math.max(...all.map(p=>p[0]));
  const minY=Math.min(...all.map(p=>transform(p[1]))),maxY=Math.max(...all.map(p=>transform(p[1])));
  const x=(v:number)=>50+(v-minX)/(maxX-minX||1)*550,y=(v:number)=>155-(transform(v)-minY)/(maxY-minY||1)*130;
  return <div className="trace-chart"><svg viewBox="0 0 620 195" role="img" aria-label={label}>{[0,.5,1].map(f=><g key={f}><line x1="50" x2="600" y1={25+f*130} y2={25+f*130} stroke="#2d3c49"/><text x="4" y={30+f*130} fill="#94a6b8" fontSize="11">{logarithmic?`10^${(maxY-f*(maxY-minY)).toFixed(1)}`:fmt(maxY-f*(maxY-minY),3)}</text></g>)}{series.map(s=><polyline key={s.name} points={s.values.filter(p=>Number.isFinite(p[1])&&(!logarithmic||p[1]>0)).map(p=>`${x(p[0])},${y(p[1])}`).join(' ')} fill="none" stroke={s.color} strokeWidth="1.8"/>)}<text x="50" y="180" fill="#94a6b8" fontSize="11">{fmt(minX,3)}</text><text x="555" y="180" fill="#94a6b8" fontSize="11">{fmt(maxX,3)}</text></svg><div className="chart-key">{series.map(s=><span key={s.name}><i style={{background:s.color}}/>{s.name}</span>)}<small>{xLabel}</small></div></div>;
}
export default function RunDetails({run,logs}:{run:any;logs:string[]}){
  const result=run?.result; const m=result?.metrics||{};
  const common=[['Mass imbalance','mass_imbalance','fraction']];
  const byUse:Record<string,string[][]>={pipe:[['Outlet volume flow','outlet_volume_flow_m3s','m³/s'],['Outlet mass flow','outlet_mass_flow_kgs','kg/s'],['Inlet static pressure','inlet_pressure_pa','Pa gauge'],['Outlet static pressure','outlet_pressure_pa','Pa gauge'],['Static pressure drop','pressure_drop_pa','Pa'],['Total-pressure loss','total_pressure_loss_pa','Pa'],['Equivalent head loss','head_loss_m','m']],aerodynamics:[['Drag','drag_n','N'],['Lift','lift_n','N'],['Drag coefficient','cd',''],['Lift coefficient','cl','']],propeller:[['Rotor thrust','thrust_n','N'],['Fluid torque · positive axis','fluid_torque_nm','N·m'],['Required driving torque','torque_nm','N·m'],['Required shaft power','shaft_power_w','W'],['Propulsive efficiency','efficiency',''],['Thrust coefficient','ct',''],['Torque coefficient','cq','']]};
  const quantities=byUse[run?.spec.use_case?.kind];

  return <div className="run-details"><div className="details-heading"><div><span className="eyebrow">SIMULATION RECORD</span><h2>{run?.spec.name||'No run selected'}</h2></div>{run&&<span className={`run-badge ${run.status}`}>{run.status} · {run.stage}</span>}</div>
    {run?.error&&<p className="finding fail">{run.error}</p>}
    {result?.metrics&&<><div className="metrics-grid">{[...(quantities||[...byUse.aerodynamics,...byUse.propeller,...byUse.pipe]),...common].map(([name,key,unit])=><div key={key} title={result.analysis?.definitions?.[key]}><span>{name}</span><strong>{fmt(key==='mass_imbalance'?result.mass_imbalance:m[key])}<small>{unit}</small></strong>{m[key]===null&&<p className="hint">{result.analysis?.unavailable?.[key]||'Unavailable for this run'}</p>}</div>)}</div><p className="hint">{result.numerical_status==='checks_passed'?'Numerical checks passed.':'Numerical quality needs review.'} Experimental template validation remains pending. “—” indicates an unavailable or undefined quantity.</p>
      <div className="chart-grid"><section><h3>Initial residuals</h3><TraceChart label="Residual history" logarithmic series={['p','Ux','Uy','Uz','k','omega'].map((field,i)=>({name:field,color:['#77e5c3','#89b9ff','#d5a8ff','#edba76','#ff9595','#bdd66d'][i],values:(result.residuals||[]).filter((r:any)=>r.field===field).map((r:any)=>[r.iteration,r.initial])}))}/></section><section><h3>Force stability</h3><TraceChart label="Force history in newtons" series={run.spec.use_case?.kind==='aerodynamics'&&result.projected_history?.length?['drag_n','lift_n'].map((key,i)=>({name:i?'Lift':'Drag',color:i?'#89b9ff':'#77e5c3',values:result.projected_history.map((r:any)=>[r.iteration,r[key]])})):['Fx','Fy','Fz'].map((name,i)=>({name,color:['#77e5c3','#89b9ff','#edba76'][i],values:(result.history||[]).map((r:any)=>[r.iteration,r.force[i]])}))}/></section></div>
      {run.spec.rotation.enabled&&<><p className="hint">Thrust follows the saved thrust axis. Fluid torque is about the rotor origin, projected on the positive rotation axis. Driving torque is positive in the commanded rotation direction. Efficiency is undefined at zero advance speed.</p><TraceChart label="Rotor thrust history" series={[{name:'Thrust · N',color:'#71e1c3',values:(result.rotor_history||[]).map((r:any)=>[r.iteration,r.force.reduce((sum:number,n:number,i:number)=>sum+n*run.spec.references.thrust_axis[i],0)])}]}/>{result.rotor_load_history?.length>0&&<TraceChart label="Rotor torque history" series={['fluid_torque_nm','torque_nm'].map((key,i)=>({name:i?'Driving torque · N·m':'Fluid torque · N·m',color:i?'#edba76':'#89b9ff',values:result.rotor_load_history.map((r:any)=>[r.iteration,r[key]])}))}/>}</>}
      {run.spec.mode==='internal'&&<p className="hint">Pressure is gauge Pa. Static pressure drop and total-pressure loss are separate measurements. Head loss uses 9.80665 m/s² with no elevation correction. Fluxes are positive out of the domain.</p>}
      {!!Object.keys(result.components||{}).length&&<details><summary>Component loads</summary><div className="table-scroll"><table><thead><tr><th>Surface</th><th>Fx · N</th><th>Fy · N</th><th>Fz · N</th></tr></thead><tbody>{Object.entries(result.components).map(([name,v]:any)=><tr key={name}><td>{name}</td>{v.force.map((n:number,i:number)=><td key={i}>{fmt(n)}</td>)}</tr>)}</tbody></table></div></details>}
    </>}
    {run&&<details open={run.status==='running'||run.status==='failed'}><summary>Execution log <small>{run.id.slice(0,8)}</small></summary><pre className="log-output">{logs.length?logs.join('\n'):'No log events recorded.'}</pre></details>}
  </div>;
}
